### ISSUE TITLE
Runtime Error in `sema-bench` with Previously Working Configuration

### ISSUE THREAD

**Issue by cedricdcc** [vliz-be-opsci/py-sema#153]
A runtime error has started occurring in the `sema-bench` component, where no issues were previously observed. The error appears when using the following `sembench-config.yml`:  

```yaml
travharv_task:
  func: harvest
  args:
    config: /data/travharv_config/
    target_store_info:
      - http://graphdb:7200/repositories/kgap
      - http://graphdb:7200/repositories/kgap/statements
sync_task:
  func: sync-fs-triples
  args:
    root: /data
    read_uri: http://graphdb:7200/repositories/kgap
    write_uri: http://graphdb:7200/repositories/kgap/statements
```

and `travharv-config.yml`:  

```yaml
snooze-till-graph-age-minutes: 100000
prefix:
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  dcat: http://www.w3.org/ns/dcat#
  schema: https://schema.org/
  org: http://www.w3.org/ns/org#
  dct: http://purl.org/dc/terms/
  mi: http://www.marineinfo.org/ns/ontology#
assert:
  - subjects:
      literal:
        - https://data.emobon.embrc.eu
    paths:
      - "schema:person / schema:name"
  - subjects:
      SPARQL: >
        SELECT DISTINCT ?o
        WHERE {
              ?s schema:itemListElement ?o .
              }
    paths:
      - "*"
  - subjects:
      SPARQL: >
        SELECT DISTINCT ?o
        WHERE {
              ?s schema:hasPart ?o .
              FILTER regex(str(?o), ".*\\.ttl$")
              }
    paths:
      - "*"
  - subjects:
      SPARQL: >
        PREFIX owl: <http://www.w3.org/2002/07/owl#> 
        PREFIX sosa: <http://www.w3.org/ns/sosa/>
        SELECT DISTINCT ?unit
        WHERE  {
          ?observations a sosa:Observation .
            ?observations sosa:observedProperty ?property .
            ?observationresult <http://qudt.org/schema/qudt/unit> ?unit .
            ?observationresult <http://qudt.org/schema/qudt/numericValue> ?resultnumeric .
            ?observations sosa:hasResult ?observationresult .
            ?observations sosa:hasFeatureOfInterest ?sample .
            ?sample sosa:hasResult ?metadatasample .
        }
    paths:
      - "*"
  - subjects:
      SPARQL: >
        PREFIX owl: <http://www.w3.org/2002/07/owl#> 
        PREFIX sosa: <http://www.w3.org/ns/sosa/>
        SELECT DISTINCT ?property
        WHERE  {
          ?observations a sosa:Observation .
            ?observations sosa:observedProperty ?property .
            ?observationresult <http://qudt.org/schema/qudt/unit> ?unit .
            ?observationresult <http://qudt.org/schema/qudt/numericValue> ?resultnumeric .
            ?observations sosa:hasResult ?observationresult .
            ?observations sosa:hasFeatureOfInterest ?sample .
            ?sample sosa:hasResult ?metadatasample .
        }
    paths:
      - "*"
```

#### Expected Behavior  
This configuration was previously working without issues. The expected behavior is that `sema-bench` runs successfully without errors.

#### Current Behavior  
A runtime error occurs when running `sema-bench` with this configuration. The details of the error need further investigation.

#### Steps to Reproduce  
1. Use the provided `sembench-config.yml` and `travharv-config.yml` files.  
2. Run `sema-bench`.  
3. Observe the runtime error.  

#### Suggested Fix  
- Verify if the provided YAML configurations are valid.  
- Introduce a new test case that specifically tests this configuration in CI to prevent regressions.  
- The `travharv-config.yml` parameters (such as `snooze-till-graph-age-minutes`) can be adjusted to optimize test runtime.  

#### Questions  
- Are the YAML files correctly formatted?  
- What recent changes might have introduced this regression?
